# 数据库连接配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lost?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: LGlws10160706@

# MyBatis-Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true  # 数据库下划线自动转Java驼峰命名
  global-config:
    db-config:
      logic-delete-field: is_delete      # 全局逻辑删除字段名
      logic-delete-value: 1              # 逻辑删除值
      logic-not-delete-value: 0          # 逻辑未删除值

# 服务器端口
server:
  port: 8080